### ISSUE TITLE
Stats are not being returned

### ISSUE THREAD

**Issue by basiclines** [yuanqing/figma-plugins-stats#3]
It happens both using the CLI:

```bash
figma-plugins-stats basiclines                                                                                !6278
error invalid json response body at https://www.figma.com/api/profile_handle/basiclines reason: Unexpected token < in JSON at position 0
```

And the API through NodeJS require functions:

```bash
(node:2755) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://www.figma.com/api/profile_handle/basiclines reason: Unexpected token < in JSON at position 0
12
    at /home/runner/work/figma-plugin-stats-notify/figma-plugin-stats-notify/node_modules/node-fetch/lib/index.js:272:32
13
    at process._tickCallback (internal/process/next_tick.js:68:7)
14
(node:2755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
15
(node:2755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yuanqing** [comment]
Unable to repro with the latest `figma-plugins-stats@0.0.15`:

```
$ npx figma-plugins-stats basiclines
npx: installed 79 in 5.477s

  period  7d
  from    2020-05-09 14:09:57 UTC+8
  to      2020-05-16 20:36:55 UTC+8

  no  name           publisher        installs              likes
  1   Super Tidy     Ismael Gonzalez  ▆▆████▆▃ 28,511 ↑698  █▄▁▁▁▄█▄ 129 ↑7
  2   Content Buddy  Ismael Gonzalez  ▇▇▅█▇█▇▂ 8,705  ↑183  █▁▁▁▁▄▁▁ 38  ↑3
  3   Linky          Ismael Gonzalez  ▂█▆▅▃▆▃▁ 69     ↑40   ▁█▁▁▁▁▁▁ 13  ↑1

                     totals           ▇▆████▆▂ 37,285 ↑921  █▄▁▁▁▄▄▂ 180 ↑11

```

(Figma made some internal API changes a couple days ago that necessitated some changes to this module.)

**Comment by basiclines** [comment]
Thank you for the quick response, it is working correctly with the 0.0.15!
